### ISSUE TITLE
US 02.02.01 - Photograph for reason

### ISSUE THREAD

**Issue by TaylorZowtuk** [CMPUT301F19T09/vibes#7]
#### Focus:
Other Mood Details

#### Partial User Story:
As a participant, I want to express the reason why for a mood event using a photograph.

#### Rationale:
* A picture is worth a thousand words.
* Can give context to the physical reasons for a mood.
* Visuals can stimulate memory thus aiding in recalling reasons for mood.

#### Clarifications:
Q1: Can a reason be both a picture and text or is it one or the other?
A1: [US 02.01.01 and 02.02.01 Both reasons may be present for the same mood event.](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1237781&parent=3254730)

#### Story Points:
2

#### Risk Level:
High

#### Testing:
* Specify a picture for the reason of a mood; should allow.
* Specify some non-image format file for the reason of a mood; should not allow.
* (Test depending on the answer to Q1)

**Comment by TaylorZowtuk** [comment]
Decided that this work can come after we establish mood events.

**Comment by adriancleung** [comment]
Error when adding photo reason. Cannot see image in mood detail.
```
2019-11-27 11:20:27.240 21103-21361/com.cmput301f19t09.vibes E/StorageException: StorageException has occurred.
    Object does not exist at location.
     Code: -13010 HttpResult: 404
2019-11-27 11:20:27.242 21103-21361/com.cmput301f19t09.vibes E/StorageException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
    java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
        at com.google.firebase.storage.network.NetworkRequest.parseResponse(com.google.firebase:firebase-storage@@19.1.0:433)
        at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(com.google.firebase:firebase-storage@@19.1.0:450)
        at com.google.firebase.storage.network.NetworkRequest.processResponseStream(com.google.firebase:firebase-storage@@19.1.0:441)
        at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@19.1.0:272)
        at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@19.1.0:286)
        at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@19.1.0:70)
        at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@19.1.0:62)
        at com.google.firebase.storage.GetDownloadUrlTask.run(com.google.firebase:firebase-storage@@19.1.0:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by adriancleung** [comment]
Well done by @JoshSabet. Looks AWESOME!! #120
